pipeline:

  environment: dev

  spark_pool: small

  bronze_path: abfss://bronze@stretaildev.dfs.core.windows.net/

  silver_path: abfss://silver@stretaildev.dfs.core.windows.net/

  gold_path: abfss://gold@stretaildev.dfs.core.windows.net/
