# File: config/star_schema.yaml

fact_tables:
  - FactSales
  - FactOrdersSnapshot

dimensions:
  - DimCustomer
  - DimProduct
  - DimDate
  - DimStore

relationships:
  FactSales:
    - CustomerSK -> DimCustomer.CustomerSK
    - ProductSK -> DimProduct.ProductSK
    - StoreSK -> DimStore.StoreSK
    - DateKey -> DimDate.DateKey
